### ISSUE TITLE
Class 'Versio' not found

### ISSUE THREAD

**Issue by chrisriteco** [Cannonb4ll/laravel-versio#1]
Gives me the error 'Class 'Versio' not found' with Laravel 5. Project compatible with Laravel 5?

**Comment by Cannonb4ll** [comment]
Will look into this tommorow, thank you.

**Comment by chrisriteco** [comment]
Please let me know if i can test or help you with something.

**Comment by Cannonb4ll** [comment]
Can you try to add `use LaravelVersio\Versio;` before using new Versio?

**Comment by chrisriteco** [comment]
I have it working now. 
- Added the 'use LaravelVersio\Versio;'.
- Convert the Versio password to a sha1 hash in the .env. (readme thing or you can sha1 in the code)
- Edited the helpers.php to a valid php-file (simple '<?php //somecomment ?>')to solve the error below with the command 'composer update' -> Illuminate\Foundation\ComposerScripts::postUpdate
  PHP Parse error:  syntax error, unexpected end of file in 'vendor/cannonb4ll/laravel-versio/src/Utilities/helpers.php on line 1'

**Comment by Cannonb4ll** [comment]
Should be all resolved by now. I have done some more tweaks to this package just now.
